### ISSUE TITLE
ReadingActivityLog

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PACOR#117]
我們還沒確實的做記錄呢

**Comment by pulipulichen** [comment]
下一個要處理的是這個

**Comment by pulipulichen** [comment]
FAILED 

  total       : 133
  passed      : 73
  failed      : 60
  time        : 19s

嚇死人多的測試失敗！！

**Comment by pulipulichen** [comment]
有問題的

Model/User.getReadingProgresses
User.getUserIDsInGroup.spec.js
這個可能是受到快取的影響吧...

**Comment by pulipulichen** [comment]
total       : 134
  passed      : 73
  failed      : 61
  time        : 24s

錯誤又增加了...

**Comment by pulipulichen** [comment]
Seed.spec通過了

**Comment by pulipulichen** [comment]
Models

  total       : 17
  passed      : 8
  failed      : 9
  time        : 3s

**Comment by pulipulichen** [comment]
````
Trace: CacheHelper error null Models.Webpage.getStepConfig.1
    at Promise (D:\xampp\htdocs\projects-nodejs\PACOR\app\Helpers\CacheHelper.js:230:15)
Error: SyntaxError: Unexpected token u in JSON at position 0
    at Promise (D:\xampp\htdocs\projects-nodejs\PACOR\app\Helpers\CacheHelper.js:231:13)
````

**Comment by pulipulichen** [comment]
又突然可以跑了...

**Comment by pulipulichen** [comment]
````
  total       : 5
  passed      : 3
  failed      : 2
  time        : 1s
````

還可以接受

**Comment by pulipulichen** [comment]
Model最後一個也可以了，再來一起跑看看

**Comment by pulipulichen** [comment]
````
   PASSED 

  total       : 17
  passed      : 17
  time        : 4s
Done.
````
總算...總算走到這一天了...

Models克服！！

**Comment by pulipulichen** [comment]
````
  total       : 86
  passed      : 38
  failed      : 48
  time        : 17s
````
悲慘到不行

**Comment by pulipulichen** [comment]
````
  total       : 113
  passed      : 88
  failed      : 25
  time        : 17s
````
其實意外的很少了

**Comment by pulipulichen** [comment]
Annotation.spec
````
  total       : 22
  passed      : 18
  failed      : 4
  time        : 4s
````

好，加油

**Comment by pulipulichen** [comment]
我們先...把位置移動一下好了
換另一個issue
