### ISSUE TITLE
寫完小節筆記之後，不知道為什麼要很久才會換下一篇

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PACOR#142]

**Comment by pulipulichen** [comment]
ReadingProgress.end 3
這之間要非常久
ReadingProgress.end 4

**Comment by pulipulichen** [comment]
````js
console.log('endReadingProgress', 7, (new Date).getSeconds())
        //let status = await this.getReadingProgressStatus(webpage)
        //console.log('after update', status)
        //console.log('prev step', this.username, step.step_name)
        //console.log('prev step', this.username, step.step_name)
        //console.log('step.end_timestamp CCC', time)
        step = await this.startReadingProgress(webpage)
        
        console.log('endReadingProgress', 8, (new Date).getSeconds())
````

**Comment by pulipulichen** [comment]
````
startReadingProgress 1 52:48 
  at Object.getStackTraceString (D:\xampp\htdocs\projects-nodejs\PACOR\app\Helpers\ExceptionHelper.js:18:26)
  at Proxy.Model.startReadingProgress (D:\xampp\htdocs\projects-nodejs\PACOR\app\Models\Traits\User\UserReadingProgressAction.js:15:87)
  at Proxy.Model.addActivitySeconds (D:\xampp\htdocs\projects-nodejs\PACOR\app\Models\Traits\User\UserReadingProgressAction.js:164:29)
  at ReadingProgress.activityTimer (D:\xampp\htdocs\projects-nodejs\PACOR\app\Controllers\Http\client\ReadingProgress.js:50:16)
  at controllerMapping (D:\xampp\htdocs\projects-nodejs\PACOR\start\routes.js:68:36)
  at Route.any (D:\xampp\htdocs\projects-nodejs\PACOR\start\routes.js:130:10)
  at Server._routeHandler (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\@adonisjs\framework\src\Server\index.js:121:31)
  at MiddlewareBase._resolveMiddleware (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\@adonisjs\middleware-base\index.js:195:28)
  at Runnable._invoke (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\co-compose\src\Runnable.js:76:42)
  at once (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\co-compose\src\Runnable.js:73:34)
  at f (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\once\once.js:25:25)
  at WebpageParser.handle (D:\xampp\htdocs\projects-nodejs\PACOR\app\Middleware\WebpageParser.js:15:11)
startReadingProgress 2 52:48
startReadingProgress 2.2 52:48 CollaborativeReading
startReadingProgress 4 52:48
startReadingProgress 5 52:48
startReadingProgress 11 52:48 
  at Object.getStackTraceString (D:\xampp\htdocs\projects-nodejs\PACOR\app\Helpers\ExceptionHelper.js:18:26)
  at Proxy.Model.startReadingProgress (D:\xampp\htdocs\projects-nodejs\PACOR\app\Models\Traits\User\UserReadingProgressAction.js:58:88)
````

**Comment by pulipulichen** [comment]
問題是
````
await webpage.addNotification(this, {
            triggerInstance: step
          })
````
太花時間了

有辦法讓它簡單一點嗎？

**Comment by pulipulichen** [comment]
好，有，他有運作
