### ISSUE TITLE
Highlight的部分壓縮

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PACOR#160]
跟昨晚的做法一樣，每種type畫成一個map，畫完後再來作merge

**Comment by pulipulichen** [comment]
![image](https://user-images.githubusercontent.com/2345913/70391588-bd3ed800-1a11-11ea-939e-f22235674ca3.png)

理想要這樣

**Comment by pulipulichen** [comment]
81
是誰？

**Comment by pulipulichen** [comment]
212-262
seq_id = 4

**Comment by pulipulichen** [comment]
![image](https://user-images.githubusercontent.com/2345913/70392423-f16ac680-1a1a-11ea-9efc-5e729d3e712b.png)

**Comment by pulipulichen** [comment]
可行，來做一次大規模測試
這次跑40個應該都沒問題了

**Comment by pulipulichen** [comment]
````
[38: c1. pre image]  Evaluation failed: Error:
Error from puppeteer: Error: Node is either not visible or not an HTMLElement
Element length: 1
Element classList: ui button questionnaire-submit ui green right labeled icon bu
tton PACORTestManagerInteractions-1575824747492
Element DOM path:
  at exec (http://127.0.0.1:4000/spa/client.js:3475:24)
    at exec (http://127.0.0.1:4000/spa/client.js:3471:15)
[7: d2. 隨意寫標註]  Evaluation failed:
Element not found: .CompactNavigation .CompactMenu:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
[13: d2. 隨意寫標註]  Evaluation failed:
Element not found: .CompactNavigation .CompactMenu:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
[1: d2. 隨意寫標註]  Evaluation failed:
Element not found: .CompactNavigation .CompactMenu:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
[22: d2. 隨意寫標註]  Evaluation failed:
Element not found: .CompactNavigation .CompactMenu:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
[29: d2. 隨意寫標註]  Evaluation failed:
Element not found: .CompactNavigation .CompactMenu:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
````

**Comment by pulipulichen** [comment]
````

[1: c1. pre image]  Evaluation failed: Error:
Error from puppeteer: Error: Node is either not visible or not an HTMLElement
Element length: 1
Element classList: ui button questionnaire-submit ui green right labeled icon bu
tton PACORTestManagerInteractions-1575825245268
Element DOM path:
  at exec (http://127.0.0.1:4000/spa/client.js:3475:24)
    at exec (http://127.0.0.1:4000/spa/client.js:3471:15)
[37: d2. 隨意寫標註]  Evaluation failed:
Element not found: .CompactNavigation .CompactMenu:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
[25: d3. 處理檢核單]  Evaluation failed:
有看到撰寫小節重點嗎？是不是送出小節checklist的時間太久了？
Element not found: .SectionAnnotationList > .ui.fluid.button:last:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
[6: d3. 處理檢核單]  Evaluation failed:
有看到撰寫小節重點嗎？是不是送出小節checklist的時間太久了？
Element not found: .SectionAnnotationList > .ui.fluid.button:last:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
````
