### ISSUE TITLE
TEST: Error from puppeteer: Error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PACOR#163]
似乎是pre image還沒完成...

````
[1: c1. pre image]  Evaluation failed: Error:
Error from puppeteer: Error: Node is either not visible or not an HTMLElement
Element length: 1
Element classList: ui button questionnaire-submit ui green right labeled icon bu
tton PACORTestManagerInteractions-1575825245268
Element DOM path:
  at exec (http://127.0.0.1:4000/spa/client.js:3475:24)
    at exec (http://127.0.0.1:4000/spa/client.js:3471:15)
````

**Comment by pulipulichen** [comment]
已經修正
