### ISSUE TITLE
TEST: 有看到撰寫小節重點嗎？是不是送出小節checklist的時間太久了？

### ISSUE THREAD

**Issue by pulipulichen** [pulipulichen/PACOR#164]
````
[25: d3. 處理檢核單]  Evaluation failed:
有看到撰寫小節重點嗎？是不是送出小節checklist的時間太久了？
Element not found: .SectionAnnotationList > .ui.fluid.button:last:visible
  at check (http://127.0.0.1:4000/spa/client.js:3659:31)
  at http://127.0.0.1:4000/spa/client.js:3664:13
````
總之先記錄下來吧

**Comment by pulipulichen** [comment]
![image](https://user-images.githubusercontent.com/2345913/71145079-32ed4400-225b-11ea-964f-44254d282214.png)

````


   ERRORS

  1. D:\xampp\htdocs\projects-nodejs\PACOR\test\functional\browser\RunThrough.sp
ec.js
  TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\puppetee
r\lib\LifecycleWatcher.js:142:21)
  -- ASYNC --
    at Frame.<anonymous> (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\pup
peteer\lib\helper.js:111:15)
    at Page.goto (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\puppeteer\l
ib\Page.js:674:49)
    at Page.<anonymous> (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\pupp
eteer\lib\helper.js:112:23)
    at BrowserRequest.end (D:\xampp\htdocs\projects-nodejs\PACOR\node_modules\@a
donisjs\vow-browser\src\Browser\Request.js:119:35)
    at process._tickCallback (internal/process/next_tick.js:68:7)

````

**Comment by pulipulichen** [comment]
已經修正，沒有這個問題了
